# Generated by Django 3.0.4 on 2020-03-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(default='Screenshot-from-2020-03-25-12-18-42.png', max_length=100),
        ),
    ]
