# Generated by Django 3.0.4 on 2020-03-29 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200329_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authtoken',
            old_name='user_id',
            new_name='user',
        ),
    ]
