# Generated by Django 3.0.4 on 2020-03-29 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
