# Generated by Django 3.0.4 on 2020-03-30 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200329_0713'),
        ('blogs', '0006_auto_20200330_0533'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogLikes',
            new_name='Likes',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='likes',
            new_name='likes_count',
        ),
    ]
